version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: flutter_crud
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  express-server:
    build: ./express-server
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: flutter_crud

  flutter-app:
    build: ./flutter_app
    ports:
      - "8080:8080"
    depends_on:
      - express-server

volumes:
  mysql-data:
